name: Publish Website
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '22.x'
    - name: Install npm dependencies
      run: npm ci
    - name: Run cache update task
      run: npm run cache-update --if-present
    - name: Run build task
      run: npm run build --if-present
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/